<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Student Performance Prediction – Yolanda Wu</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yolanda Wu</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1 Introduction</a>
  <ul class="collapse">
  <li><a href="#research-question-of-interest" id="toc-research-question-of-interest" class="nav-link" data-scroll-target="#research-question-of-interest">1.1 Research Question of Interest</a></li>
  <li><a href="#background-and-source-of-the-data-set" id="toc-background-and-source-of-the-data-set" class="nav-link" data-scroll-target="#background-and-source-of-the-data-set">1.2 Background and Source of the Data Set</a></li>
  </ul></li>
  <li><a href="#explain-the-method-chosen-to-model-the-relationship" id="toc-explain-the-method-chosen-to-model-the-relationship" class="nav-link" data-scroll-target="#explain-the-method-chosen-to-model-the-relationship">1.3 Explain the method chosen to model the relationship</a></li>
  <li><a href="#overview-of-the-structure-of-our-research" id="toc-overview-of-the-structure-of-our-research" class="nav-link" data-scroll-target="#overview-of-the-structure-of-our-research">1.4 Overview of the structure of our research</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">2 Data Description</a></li>
  <li><a href="#results-and-interpretation" id="toc-results-and-interpretation" class="nav-link" data-scroll-target="#results-and-interpretation">3 Results and Interpretation</a>
  <ul class="collapse">
  <li><a href="#original-model-diagnostics" id="toc-original-model-diagnostics" class="nav-link" data-scroll-target="#original-model-diagnostics">3.1 Original Model Diagnostics</a></li>
  <li><a href="#final-model-diagnostics" id="toc-final-model-diagnostics" class="nav-link" data-scroll-target="#final-model-diagnostics">3.2 Final Model Diagnostics</a></li>
  </ul></li>
  <li><a href="#summary-and-further-analysis" id="toc-summary-and-further-analysis" class="nav-link" data-scroll-target="#summary-and-further-analysis">4 Summary and Further Analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Student Performance Prediction</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>More details decribed in <a href="https://github.com/Yolandayx929/Predicting-Student-Performance-in-Portuguese-Secondary-Schools">here</a>.</p>
<section id="introduction" class="level1">
<h1>1 Introduction</h1>
<p>In recent years, predicting student performance has become increasingly important for both educators and policymakers. In this project, we seek to determine the most influential predictors on a student’s final grade in Portuguese secondary schools using a combination of students’ physical and school-related factors.</p>
<section id="research-question-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="research-question-of-interest">1.1 Research Question of Interest</h2>
<p>Our research question is: Can we accurately predict students’ final grades based on their time of study, family members’ education level, students’ health condition and number of absences? This question was formulated considering its potential implications for early interventions in a student’s academic journey. For instance, understanding what non-academic factors contribute significantly to final grades could help schools and policymakers design effective support systems to improve student performance.</p>
</section>
<section id="background-and-source-of-the-data-set" class="level2">
<h2 class="anchored" data-anchor-id="background-and-source-of-the-data-set">1.2 Background and Source of the Data Set</h2>
<p>The data we use in this project was collected from two Portuguese secondary schools and includes a variety of student grades, family-related and school-related attributes. In this report, we start by providing a descriptive analysis of the data, then move on to fit and interpret multiple regression models to answer our research question, and finally discuss our findings and their implications. The variables include:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 32%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Description</th>
<th>Options</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Medu</td>
<td>Mother’s Education</td>
<td>1 - None, 2 - Primary, 3 - Secondary, 4 - College</td>
</tr>
<tr class="even">
<td>Fedu</td>
<td>Father’s Education</td>
<td>1 - None, 2 - Primary, 3 - Secondary, 4 - College</td>
</tr>
<tr class="odd">
<td>studytime</td>
<td>Weekly Study Time</td>
<td>1 - &lt;2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, 4 - &gt;10 hours</td>
</tr>
<tr class="even">
<td>health</td>
<td>Current Health Status</td>
<td>1 - Very Bad, 2, 3, 4, 5 - Very Good</td>
</tr>
<tr class="odd">
<td>absences</td>
<td>Number of Absences</td>
<td>0 to 93</td>
</tr>
<tr class="even">
<td>G1</td>
<td>First-Period Grade</td>
<td>0 to 20</td>
</tr>
<tr class="odd">
<td>G2</td>
<td>Second-Period Grade</td>
<td>0 to 20</td>
</tr>
<tr class="even">
<td>G3</td>
<td>Final Grade</td>
<td>0 to 20</td>
</tr>
<tr class="odd">
<td>Gtotal</td>
<td>Total Grade</td>
<td>0 to 60</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>[!TIP] The latest version of this project report, datasets and R source code files are available in this GitHub repository.</p>
</blockquote>
</section>
</section>
<section id="explain-the-method-chosen-to-model-the-relationship" class="level1">
<h1>1.3 Explain the method chosen to model the relationship</h1>
<p>While modeling the relationship between different variables, we begin with the Multiple Linear Regression (MLR) and diagnostic plots. To better the model, we use transformation and model selection for MLR. After getting the final model, we check the improvements by viewing the general diagnostic plots.</p>
</section>
<section id="overview-of-the-structure-of-our-research" class="level1">
<h1>1.4 Overview of the structure of our research</h1>
<p>We begin the paper with scatter plots for the data to show the general relationship between the response variable (Gtotal) and all predictors. Then we use the R results to comment on the fit of the linear model and find a better model for the data set. Finally, we summarize the results by discussing the limitations and expectations of our model.</p>
</section>
<section id="data-description" class="level1">
<h1>2 Data Description</h1>
<p>The Figure 2.1 shows the correlations relationship between each variable.</p>
<p>The summary statistics of these variables such as mean, standard deviation, distribution of each variable and relationships among the variables using appropriate graphs are attached in Appendix II.</p>
</section>
<section id="results-and-interpretation" class="level1">
<h1>3 Results and Interpretation</h1>
<section id="original-model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="original-model-diagnostics">3.1 Original Model Diagnostics</h2>
<p>Based on the scatter plot (Figure 2.1) and summary result (Tab 3.1), we learn about the relationship between response variable and all predictors. We can learn from scatter plot and summary result that except for the educational levels of fathers, all other variables are statistically significant.</p>
<p><strong>Tab 3.1</strong> Summary Result of Original Model</p>
<pre><code>Call:
lm(formula = Gtotal ~ Medu + Fedu + studytime + health + absences, 
    data = student)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.5097  -4.4600  -0.2166   4.0884  17.7181 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 31.09306    1.73540  17.917  &lt; 2e-16 ***
Medu         1.21202    0.38351   3.160 0.001691 **
Call:
lm(formula = Gtotal ~ Medu + Fedu + studytime + health + absences, 
    data = student)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.5097  -4.4600  -0.2166   4.0884  17.7181 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 31.09306    1.73540  17.917  &lt; 2e-16 ***
Medu         1.21202    0.38351   3.160 0.001691 ** 
Fedu         0.25086    0.37613   0.667 0.505165    
studytime    1.82387    0.38853   4.694 3.64e-06 ***
health      -0.67388    0.22628  -2.978 0.003070 ** 
absences    -0.24260    0.06267  -3.871 0.000126 ***
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Residual standard error: 6.564 on 417 degrees of freedom
Multiple R-squared:  0.1634,    Adjusted R-squared:  0.1534 
F-statistic: 16.29 on 5 and 417 DF,  p-value: 1.089e-14</code></pre>
<p>Based on the diagnostic plots (see Appendix I, Figure I.1), we know that the variance of residuals is not constant and there are some bad leverage points. Thus, this model is not valid and needs to be modified. Then we use the R code result (Table 3.2) to determine the transformation needed for each variable. Since for the variable of absence, there are 0 values that hinder our function, we add 1 to all absence values.</p>
<p><strong>Tab 3.2</strong> Transformation Results for each variable</p>
<pre><code>bcPower Transformations to Multinormality 
          Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd
Gtotal       0.6166        1.00       0.2193       1.0140
Medu         1.2951        1.00       0.9946       1.5956
Fedu         0.7896        1.00       0.5172       1.0619
studytime    0.1993        0.00      -0.0206       0.4192
health       1.4179        1.42       1.1839       1.6518
            -0.0531        0.00      -0.1634       0.0572
Likelihood ratio test that transformation parameters are equal to 0
 (all log transformations)
                                    LRT df       pval
LR test, lambda = (0 0 0 0 0 0) 304.811  6 &lt; 2.22e-16

Likelihood ratio test that no transformations are needed
                                     LRT df       pval
LR test, lambda = (1 1 1 1 1 1) 468.6497  6 &lt; 2.22e-16</code></pre>
<p>Based on the rounded power in R result, we can get the transformed model to be: <span class="math inline">\(`Gtotal = β_0+ β_1× Medu + β_2× Fedu + β_3×log⁡(studytime)+ β_4× health^{1.42}+ β_5×log⁡(absences +1)`\)</span></p>
<p><strong>Tab 3.3</strong> Summary Result of Transformed Model</p>
<pre><code>Call:
lm(formula = Gtotal ~ Medu + Fedu + log(studytime) + I(health^(1.4)) + 
    log(absences + 1), data = student)
Residuals:
     Min       1Q   Median       3Q      Max 
-18.8946  -4.3599  -0.0842   4.2985  17.9949 
Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        32.2162     1.5458  20.842  &lt; 2e-16 ***
Medu                1.2536     0.3830   3.273  0.00115 ** 
Fedu                0.2263     0.3760   0.602  0.54754    
log(studytime)      3.6824     0.7561   4.870 1.59e-06 ***
I(health^(1.4))    -0.2907     0.1030  -2.822  0.00501 ** 
log(absences + 1)  -1.1697     0.3278  -3.569  0.00040 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Residual standard error: 6.565 on 417 degrees of freedom
Multiple R-squared:  0.1631,    Adjusted R-squared:  0.153 
F-statistic: 16.25 on 5 and 417 DF,  p-value: 1.189e-14</code></pre>
</section>
<section id="final-model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="final-model-diagnostics">3.2 Final Model Diagnostics</h2>
<p>After figuring out the variable transformation, we should then move on to the variable selection process. We can use the forward stepwise method to find out the best subset model.</p>
<p><strong>Tab 3.4</strong> Result of Forward Stepwise Method</p>
<pre><code>Start:  AIC=1663.25
Gtotal ~ 1

                    Df Sum of Sq   RSS    AIC
+ log(studytime)     1   1608.67 19867 1632.3
+ Medu               1   1153.63 20322 1641.9
+ log(absences + 1)  1    942.13 20534 1646.3
+ I(health^(1.4))    1    476.34 20999 1655.8
+ Fedu               1    446.32 21029 1656.4
&lt;none&gt;                           21476 1663.2

Step:  AIC=1632.31
Gtotal ~ log(studytime)
                    Df Sum of Sq   RSS    AIC
+ Medu               1   1022.92 18844 1612.0
+ log(absences + 1)  1    576.25 19291 1621.9
+ Fedu               1    468.35 19399 1624.2
+ I(health^(1.4))    1    321.10 19546 1627.4
&lt;none&gt;                           19867 1632.3

Step:  AIC=1611.95
Gtotal ~ log(studytime) + Medu

                    Df Sum of Sq   RSS    AIC
+ log(absences + 1)  1    518.66 18325 1602.2
+ I(health^(1.4))    1    312.59 18532 1606.9
&lt;none&gt;                           18844 1612.0
+ Fedu               1      3.80 18840 1613.9

Step:  AIC=1602.15
Gtotal ~ log(studytime) + Medu + log(absences + 1)
                  Df Sum of Sq   RSS    AIC
+ I(health^(1.4))  1    335.94 17990 1596.3
&lt;none&gt;                         18325 1602.2
+ Fedu             1      8.38 18317 1604.0

Step:  AIC=1596.32
Gtotal ~ log(studytime) + Medu + log(absences + 1) + I(health^(1.4))

       Df Sum of Sq   RSS    AIC
&lt;none&gt;              17990 1596.3
+ Fedu  1    15.618 17974 1598.0</code></pre>
<p>Based on the AIC values, we know that when the model is <span class="math inline">\(`Gtotal ~ log(studytime) + Medu + log(absences + 1) + I(health^1.4)`\)</span>, AIC get the smallest value. Therefore, the final model should be: <span class="math inline">\(`Gtotal = β_0  + β_1  × Medu + β_2×log(studytime) + β_3  × health^1.42  + β_4  × log(absences +1) `\)</span>. Checking on this final model, we can get the summary and diagnostic plots (see Appendix I, Figure I.2).</p>
<p><strong>Tab 3.5</strong> Summary Result of Final Model</p>
<pre><code>Call:
x

Residuals:
     Min       1Q   Median       3Q      Max 
-18.7267  -4.3258  -0.1429   4.2414  17.6855 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        32.4402     1.4991  21.639  &lt; 2e-16 ***
Medu                1.3991     0.2969   4.712 3.35e-06 ***
log(studytime)      3.6628     0.7548   4.852 1.72e-06 ***
I(health^(1.4))    -0.2871     0.1028  -2.794 0.005447 ** 
log(absences + 1)  -1.1612     0.3272  -3.549 0.000431 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Residual standard error: 6.56 on 418 degrees of freedom
Multiple R-squared:  0.1623,    Adjusted R-squared:  0.1543 
F-statistic: 20.25 on 4 and 418 DF,  p-value: 2.918e-15</code></pre>
<p>Based on the plots and summary, we know that all transformed variables in the final model are significant. Also, the variance of residuals becomes more constant, and the model has less bad leverage points.</p>
</section>
</section>
<section id="summary-and-further-analysis" class="level1">
<h1>4 Summary and Further Analysis</h1>
<p>In order to get the final model about the relationship between students’ academic performance, which is shown as the final grades in our project, and the time of study, family members’ education levels, students’ health conditions and number of absences, we use multiple linear regression model and the proper transformation and selection methods to find out the best model for our data set.</p>
<p>Based on our model, we find out that the students’ final grades are highly related to all transformed variables except the educational level of fathers. Therefore, we know that the educational levels of fathers have no relationship with students’ final grades. For the educational levels of mothers, the slope coefficient is 1.3991, which means that as mothers have higher education levels, students generally have higher final grades. Similarly, the study time also has a positive association with final grades, which indicates that as students study more, they get a better grade. However, the transformed variable of absence has a significant negative relationship with the total grades, so as students have more times of absences, they get a lower grade. The transformed variable of health also has a negative relationship with total grades, but the coefficient is not large enough. In this case, we can assume that when students have better health conditions, they perform worse academically, but this actually has little impact on the academic performance. We think our model makes sense in real life. Fathers hardly ever pay attention to their kids’ study so the fathers’ educational level has no relationship with students’ academic scores. However, mothers devote most of their time to kids, so their educational levels will greatly affect how they treated their kids’ study. Therefore, as mothers have higher educational levels, like college, they pay more attention and more money for kids’ study, which greatly improves their academic performance. It’s obvious that absences will negatively influence students’ final scores because they miss some key points while they are away from class. Poorer health conditions may be related with higher graders because unhealthy kids have more time staying at home and learning things.</p>
<p>Despite all the achievements we have made, our project has some drawbacks. We want to study how different variables affect students’ final grades and academic performance. However, we only get the data from two Portuguese secondary schools which means we cannot apply this model to all secondary schools students. If some elements are different, like the size of the school or even the place where the school is located, the result may be very different. Therefore, in order to improve the model, we should collect students’ data from secondary schools of different sizes and at different places.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2024 Yolanda Wu.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>