project:
  type: website

website:
  title: "Yolanda Wu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects

  page-footer:
    left: "© Copyright 2024 Yolanda Wu."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em

execute: 
  freeze: auto

